### ISSUE TITLE
Sword never disappears

### ISSUE THREAD

**Issue by kuletxcore** [Sevelar/talesofneptunia#6]
**Describe the bug**
The equipped weapon never disappears or holsters when I get out of Battle mode

**To Reproduce**
1. Enter "Battle Mode" (Press B)
2. Exit Battle mode (Press B again)
3. ???
4. Watch as the weapon follows the hand.

**Expected behavior**
It is supposed to be holstered or disappear when you get out of Battle Mode

**Comment by ghost** [comment]
Thank you for informing us! We are now currently looking at the problem, and will soon resolve the bug.

**Comment by kuletxcore** [comment]
Playing with the Battle Mode bug. https://youtu.be/t7eYH_-DC74

**HOW TO REPRODUCE:**
1. Go to battle mode
2. Jump
3. Transform
4. ????
5. Repeat ad infinitum

**Comment by Sevelar** [comment]
Bug fixed. Thanks for reporting.
Check commit 9ec89d4.
