### ISSUE TITLE
Other CPUs

### ISSUE THREAD

**Issue by kuletxcore** [Sevelar/talesofneptunia#7]
**Describe the bug**
They can't jump, and in the case of HD Noire, she can't jump until she transforms.
And when Noire transforms, she can't change back.

That's it for now.

**Comment by ghost** [comment]
Thank you for informing us! We are now currently looking at the problem, and will soon resolve the bug.

**Comment by Sevelar** [comment]
I guess this issue got fixed a long time ago, since in my newest build they can jump. They only lack of animations now, but this is in plans. So for now I'm closing this issue.
