### ISSUE TITLE
Style Guide for organization purposes

### ISSUE THREAD

**Issue by kuletxcore** [Sevelar/talesofneptunia#9]
https://github.com/Allar/ue4-style-guide/blob/master/README.md
Conform to this style guide for the project to be more optimized and organized.

We need some sort of style guide. Rename and re-arrange everything. :)

Just a friendly suggestion.

**Comment by SirChopwood** [comment]
personally think this may be useful but overly complex for us. would suggest we make a much simpler file system inhouse

**Comment by kuletxcore** [comment]
> personally think this may be useful but overly complex for us. would suggest we make a much simpler file system inhouse

True.
